"""
Simulation Helpers for MM-Bracket-Flow
Generated by Research Agent for the Optimization Agent.
"""

def calculate_grit(adj_de, orb_pct, luck):
    """
    Calculates the Grit score based on 2025 specifications.
    Grit = 0.4 * (100 - AdjDE) + 0.3 * ORB_pct + 0.3 * (abs(Luck) if Luck < 0 else 0)
    """
    luck_bonus = abs(luck) if luck < 0 else 0
    return (0.4 * (100 - adj_de)) + (0.3 * orb_pct) + (0.3 * luck_bonus)

def calculate_aggression(adj_t, ft_rate, to_pct_def):
    """
    Calculates the Aggression score based on 2025 specifications.
    Aggression = 0.3 * AdjT + 0.4 * FT_Rate + 0.3 * TO_pct_def
    """
    return (0.3 * adj_t) + (0.4 * ft_rate) + (0.3 * to_pct_def)

def calculate_portal_stability(min_ret_pct, pts_ret_pct, trans_usage_pct):
    """
    Calculates Roster Stability for the NIL/Portal Era.
    Portal Stability = 0.5 * min_ret_pct + 0.3 * pts_ret_pct - 0.2 * trans_usage_pct
    """
    return (0.5 * min_ret_pct) + (0.3 * pts_ret_pct) - (0.2 * trans_usage_pct)

def calculate_moxie(pase, wins, final_fours):
    """
    Calculates the Moxie coefficient based on coach tournament history.
    """
    return (pase * 0.5) + (wins * 0.2) + (final_fours * 0.3)

def calculate_chaos_potential(three_pa_ratio, to_pct_def):
    """
    Calculates the Chaos Potential for low seeds based on variance and pressure.
    """
    return (three_pa_ratio * 0.6) + (to_pct_def * 0.4)

def apply_volatility_modifiers(base_prob, continuation_impact=None, orb_density_bonus=None, moxie_bonus=0, chaos_variance=0):
    """
    Applies 2025-specific rule and strategy modifiers.
    """
    modified_prob = base_prob
    if continuation_impact:
        modified_prob *= 1.05  # 5% boost for driving offenses
    if orb_density_bonus:
        modified_prob *= 1.03  # 3% second-chance multiplier
    
    # Apply Moxie (Coach Efficiency) bonus
    modified_prob += (moxie_bonus * 0.02)
    
    # Chaos variance (can increase or decrease prob, mostly increases upset chance)
    # This is a stub for the simulation engine to use for higher variance loops
    return modified_prob
